### ISSUE TITLE
Make imagej.app.directory outisde of pom.xml ?

### ISSUE THREAD

**Issue by hadim** [imagej/imagej-maven-plugin#14]
I would like to not track `imagej.app.directory` property by git by putting it outside the `pom.xml` file. I am using Netbeans for development and so a method compatible with it would be nice :-)

Any idea ?

**Comment by ctrueden** [comment]
Edit the file `~/.m2/settings.xml` (create if it doesn't exist), adding the following:

```xml
	<profiles>
		<profile>
			<id>imagej</id>
			<activation>
				<file>
					<exists>${env.HOME}/Desktop/Fiji.app</exists>
				</file>
			</activation>
			<properties>
				<imagej.app.directory>${env.HOME}/Desktop/Fiji.app</imagej.app.directory>
			</properties>
		</profile>
	</profiles>
```
You can use whatever `<activation>` you want. You could also have multiple profiles, one per ImageJ/Fiji installation, which you enable by `<id>` (e.g., `-Pimagej`), if needed.

Your NetBeans will then automatically pick up the profile and use it when building.

**Comment by hadim** [comment]
Exactly what I needed. Thanks !
Le 13 avr. 2016 10:38 AM, "Curtis Rueden" <notifications@github.com> a
écrit :
