### ISSUE TITLE
Improve detection of other versions

### ISSUE THREAD

**Issue by stelfrich** [imagej/imagej-maven-plugin#28]
Currently, there is a filename/regex-based check for determining if a file in `imagej.app.directory` conflicts with the artifact to be installed. While this check works, it has hardcoded patterns and is thus not extensible if e.g. artifacts with new architectures show up.

We (@ctrueden and I) have come up with the following scheme to extract the version and qualifier from a Jar file:

1. Look in Jar for version information:
   1. pom.xml in META-INF (if found, return)
   2. MANIFEST.mf (`implementation version`)
2. If the version is found in the filename suffix, the rest is a qualifier [If not: ij.jar or inconsistent: warning]
3. If nothing is in the filename
    1. use regex (dash+digit: substring) 
   2. if there is no version, assume there is a qualifier or suffix

**Comment by ctrueden** [comment]
@stelfrich Is this issue still accurate and desired to solve? If so, could you please migrate it to scijava/scijava-maven-plugin?

**Comment by stelfrich** [comment]
Closed in favor of https://github.com/scijava/scijava-maven-plugin/issues/21.
