### ISSUE TITLE
Use POM.compareTo() instead of VersionUtils.compare()

### ISSUE THREAD

**Issue by stelfrich** [imagej/imagej-maven-plugin#29]
Use [`POM.compareTo()`](https://github.com/scijava/scijava-common/blob/328b9367e6f0d95f15c620168f3f17ca55fbe689/src/main/java/org/scijava/util/POM.java#L187-L199) (introduded in https://github.com/scijava/scijava-common/commit/c02cca436460a11bbcde3fe51f062019153a756b) instead of [`VersionUtils.compare()`](https://github.com/scijava/scijava-common/blob/328b9367e6f0d95f15c620168f3f17ca55fbe689/src/main/java/org/scijava/util/VersionUtils.java#L117-L135) when checking for newer/older versions of an artifact in [`AbstractCopyJarsMojo.java#L184`](https://github.com/imagej/imagej-maven-plugin/blob/08b781aea314b9c82845a88cd9f135db86e6839d/src/main/java/net/imagej/maven/AbstractCopyJarsMojo.java#L184).

**Comment by imagejan** [comment]
Why not the other way around, use `VersionUtils.compare()` in all places where `POM.compareTo()` is currently used? As @ctrueden mentioned [on gitter](https://gitter.im/scijava/scijava-common?at=5a3cf9dfc072deaf0befe7a9):

> It is in the wrong place. We can fix it.

**Comment by stelfrich** [comment]
Good point, @imagejan!

See also https://github.com/scijava/scijava-common/issues/334.
