### ISSUE TITLE
Improve handling of incompatible versions 

### ISSUE THREAD

**Issue by stelfrich** [imagej/imagej-maven-plugin#36]
Would it make sense to at least log a warning when overriding an older version of an artifact that is incompatible (according to SemVer) with a newer one? Should this be an extra property?

Does anyone have an opinion on this, @imagejan, @ctrueden?

**Comment by ctrueden** [comment]
To know whether a warning is sufficient—or whether a property configuring behavior is necessary—we need to know the use cases to which the mojo will be put.

For end users, testing stuff in a Fiji installation, I think a warning is sufficient.

For automated systems deploying updates to update sites (see e.g. [how SciView does it](https://github.com/scenerygraphics/sciview/blob/sciview-0.1.4/populate_fiji.sh#L66)), it may make more sense for the build to fail when anything non-SemVer-compatible is detected.

**Comment by stelfrich** [comment]
> For end users, testing stuff in a Fiji installation, I think a warning is sufficient.

I guess by end users you mean developers in this particular case, @ctrueden?

> For automated systems deploying updates to update sites (see e.g. how SciView does it), it may make more sense for the build to fail when anything non-SemVer-compatible is detected.

This could be handled by an `imagej.failOnIncompatibleVersion` flag that is set to `false` per default. I think warnings should be logged in both cases and the plugin should only fail if `imagej.failOnIncompatibleVersion==true`.

**Comment by ctrueden** [comment]
@stelfrich Could you migrate this to scijava/scijava-maven-plugin if it is still applicable?

**Comment by stelfrich** [comment]
Closed in favor of https://github.com/scijava/scijava-maven-plugin/issues/22.
