### ISSUE TITLE
Teach copy-jars about `nar` artifacts

### ISSUE THREAD

**Issue by dscho** [imagej/imagej-maven-plugin#4]
When encountering a `nar` artifact, we should not just ignore it, but rather download it, then look for all platforms known to ImageJ (_win32_, _win64_, _linux32_, _linux64_ and _macosx_) and copy the respective attached artifacts -- insofar present -- into the `lib/<platform>/` subdirectory.

**Comment by ctrueden** [comment]
Closing in favor of #19. (We may not need support for NAR artifacts anymore, but we still need support for native libraries embedded in JAR artifacts.)
